[package]
name = "securestore"
version = "0.1.0"
edition = "2021"

[dependencies]
aes-gcm = "0.10"
aes = "0.8"
base64 = "0.21"
pbkdf2 = "0.12"
sha2 = "0.10"
rand = "0.8"
walkdir = "2.4"
anyhow = "1.0"
chrono = "0.4.41"
